# a = int(input())
# b = int(input())
# c = int(input())
print(f'\nЗдравствуйте, {input("Как Вас зовут?")}!')
mood = input("Как дела?\n")
print("Я за вас рада!" if mood == "хорошо" else "Всё наладится!")
